# -*- coding: utf-8 -*-
"""Fase 1 migrasi MySQL -> PostgreSQL: introspeksi skema MySQL yang SEDANG
BERJALAN (bukan parsing ulang scripts/schema_*.sql yang gaya penulisannya
beda-beda) lalu generate + terapkan CREATE TABLE setara di PostgreSQL.

Tidak menyentuh MySQL sama sekali (read-only). Aman dijalankan ulang --
DROP TABLE IF EXISTS di Postgres dulu tiap tabel sebelum CREATE ulang
(idempoten untuk tahap skema; data belum disentuh di sini, itu Fase 2
di scripts/migrate_pg_02_data.py).

Pemakaian:
    python scripts/migrate_pg_02_data.py            # semua tabel
    python scripts/migrate_pg_01_schema.py --only usulan_inpres,ijd_scoring_rules
"""
import argparse
import os
import sys

import psycopg
from dotenv import load_dotenv

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from db import db_cursor  # noqa: E402

load_dotenv()

PG_DSN = dict(
    host=os.getenv("PG_HOST"), port=int(os.getenv("PG_PORT", 5432)),
    user=os.getenv("PG_USER"), password=os.getenv("PG_PASS"),
    dbname=os.getenv("PG_DB"),
)

# MySQL data_type -> (builder yang terima row info, return tipe kolom Postgres)
def _map_type(col: dict) -> str:
    t = col["DATA_TYPE"]
    extra = (col["EXTRA"] or "").lower()
    if "auto_increment" in extra:
        # int/bigint auto_increment -> identity; ukuran mengikuti aslinya.
        # BY DEFAULT (bukan ALWAYS) -- Fase 2 migrasi data HARUS bisa
        # menyisipkan id asli dari MySQL apa adanya (banyak tabel lain
        # mereferensikannya via kolom biasa, mis. usulan_kecamatan_dilalui.
        # usulan_id -> usulan_inpres.id, bukan foreign key formal tapi
        # tetap harus konsisten), GENERATED ALWAYS menolak itu tanpa
        # OVERRIDING SYSTEM VALUE eksplisit di tiap statement.
        return "BIGINT GENERATED BY DEFAULT AS IDENTITY" if t in ("bigint",) else "INTEGER GENERATED BY DEFAULT AS IDENTITY"
    if t in ("int", "mediumint"):
        return "INTEGER"
    if t == "bigint":
        return "BIGINT"
    if t == "smallint":
        return "SMALLINT"
    if t == "tinyint":
        # tinyint(1) dipakai sbg boolean di banyak schema MySQL; sisanya smallint
        return "BOOLEAN" if col["COLUMN_TYPE"] == "tinyint(1)" else "SMALLINT"
    if t in ("decimal", "numeric"):
        prec, scale = col["NUMERIC_PRECISION"], col["NUMERIC_SCALE"]
        return f"NUMERIC({prec},{scale})" if prec is not None else "NUMERIC"
    if t in ("float",):
        return "REAL"
    if t in ("double",):
        return "DOUBLE PRECISION"
    if t in ("varchar",):
        return f"VARCHAR({col['CHARACTER_MAXIMUM_LENGTH']})"
    if t in ("char",):
        return f"CHAR({col['CHARACTER_MAXIMUM_LENGTH']})"
    if t in ("text", "mediumtext", "longtext", "tinytext"):
        return "TEXT"
    if t == "json":
        return "JSONB"
    if t in ("date",):
        return "DATE"
    if t in ("datetime", "timestamp"):
        return "TIMESTAMP"
    if t in ("time",):
        return "TIME"
    if t in ("blob", "mediumblob", "longblob", "tinyblob", "varbinary", "binary"):
        return "BYTEA"
    if t == "enum":
        return "TEXT"  # nilai valid ditegakkan via CHECK constraint terpisah, lihat _enum_check
    raise ValueError(f"Tipe MySQL belum dipetakan: {t} (kolom {col['COLUMN_NAME']})")


def _enum_values(column_type: str) -> list:
    # COLUMN_TYPE contoh: "enum('KABUPATEN','KECAMATAN','PROVINSI')"
    inner = column_type[column_type.index("(") + 1: column_type.rindex(")")]
    return [v.strip()[1:-1] for v in inner.split(",")]


def _is_boolean(col: dict) -> bool:
    return col["DATA_TYPE"] == "tinyint" and col["COLUMN_TYPE"] == "tinyint(1)"


def _default_clause(col: dict) -> str:
    d = col["COLUMN_DEFAULT"]
    extra = (col["EXTRA"] or "").lower()
    if "auto_increment" in extra:
        return ""  # sudah GENERATED ALWAYS AS IDENTITY
    if d is None:
        return ""
    # MariaDB (beda dari MySQL) mengembalikan COLUMN_DEFAULT literal 'NULL'
    # (string 4 karakter) utk kolom yg default-nya memang NULL eksplisit --
    # itu bukan default sungguhan, setara None/tanpa default.
    if d.strip().upper() == "NULL":
        return ""
    if d.upper() in ("CURRENT_TIMESTAMP", "CURRENT_TIMESTAMP()"):
        return " DEFAULT CURRENT_TIMESTAMP"
    if _is_boolean(col):
        # kolom dipetakan ke BOOLEAN (lihat _map_type) -- default MySQL 0/1
        # (kadang sudah/tidak dibungkus kutip oleh MariaDB) harus jadi
        # FALSE/TRUE, bukan literal integer (Postgres tidak implicit-cast).
        v = d.strip("'")
        return " DEFAULT " + ("TRUE" if v == "1" else "FALSE")
    # MariaDB juga sudah membungkus default string literal dgn kutip satu
    # sendiri (mis. "'AUTO'") -- pakai apa adanya, jangan dibungkus lagi.
    if len(d) >= 2 and d.startswith("'") and d.endswith("'"):
        return f" DEFAULT {d}"
    if col["DATA_TYPE"] in ("int", "bigint", "smallint", "mediumint", "decimal", "float", "double", "tinyint"):
        return f" DEFAULT {d}"
    return " DEFAULT " + "'" + str(d).replace("'", "''") + "'"


def introspect_tables(only: set | None) -> list:
    with db_cursor() as cur:
        cur.execute(
            "SELECT table_name FROM information_schema.tables "
            "WHERE table_schema = DATABASE() AND table_type='BASE TABLE' ORDER BY table_name"
        )
        tables = [r["table_name"] for r in cur.fetchall()]
    if only:
        tables = [t for t in tables if t in only]
    return tables


def build_create_table(table: str) -> str:
    with db_cursor() as cur:
        cur.execute(
            "SELECT COLUMN_NAME, DATA_TYPE, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, "
            "EXTRA, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE "
            "FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = %s "
            "ORDER BY ORDINAL_POSITION",
            (table,),
        )
        cols = cur.fetchall()
        cur.execute(
            "SELECT COLUMN_NAME FROM information_schema.key_column_usage "
            "WHERE table_schema = DATABASE() AND table_name = %s AND CONSTRAINT_NAME = 'PRIMARY' "
            "ORDER BY ORDINAL_POSITION",
            (table,),
        )
        pk_cols = [r["COLUMN_NAME"] for r in cur.fetchall()]
        cur.execute(
            "SELECT DISTINCT INDEX_NAME FROM information_schema.statistics "
            "WHERE table_schema = DATABASE() AND table_name = %s AND NON_UNIQUE = 0 AND INDEX_NAME != 'PRIMARY'",
            (table,),
        )
        unique_idx_names = [r["INDEX_NAME"] for r in cur.fetchall()]
        unique_groups = []
        for idx_name in unique_idx_names:
            cur.execute(
                "SELECT COLUMN_NAME FROM information_schema.statistics "
                "WHERE table_schema = DATABASE() AND table_name = %s AND INDEX_NAME = %s "
                "ORDER BY SEQ_IN_INDEX",
                (table, idx_name),
            )
            unique_groups.append((idx_name, [r["COLUMN_NAME"] for r in cur.fetchall()]))

    lines = []
    enum_checks = []
    for col in cols:
        pg_type = _map_type(col)
        nullable = "" if col["IS_NULLABLE"] == "YES" else " NOT NULL"
        default = _default_clause(col)
        lines.append(f'  "{col["COLUMN_NAME"]}" {pg_type}{nullable}{default}')
        if col["DATA_TYPE"] == "enum":
            vals = _enum_values(col["COLUMN_TYPE"])
            val_list = ", ".join("'" + v.replace("'", "''") + "'" for v in vals)
            enum_checks.append(f'  CHECK ("{col["COLUMN_NAME"]}" IN ({val_list}))')
    if pk_cols:
        pk_list = ", ".join('"%s"' % c for c in pk_cols)
        lines.append(f"  PRIMARY KEY ({pk_list})")
    lines.extend(enum_checks)
    ddl = f'DROP TABLE IF EXISTS "{table}" CASCADE;\nCREATE TABLE "{table}" (\n' + ",\n".join(lines) + "\n);"
    for idx_name, idx_cols in unique_groups:
        safe_idx = f"{table}_{idx_name}_uq".replace(" ", "_")
        col_list = ", ".join('"%s"' % c for c in idx_cols)
        ddl += f'\nCREATE UNIQUE INDEX "{safe_idx}" ON "{table}" ({col_list});'
    return ddl


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only", default=None, help="daftar tabel dipisah koma, default semua")
    ap.add_argument("--dry-run", action="store_true", help="cetak DDL saja, jangan eksekusi ke Postgres")
    args = ap.parse_args()
    only = set(args.only.split(",")) if args.only else None

    tables = introspect_tables(only)
    print(f"Tabel yang diproses ({len(tables)}): {', '.join(tables)}", file=sys.stderr)

    pg_conn = None if args.dry_run else psycopg.connect(**PG_DSN, autocommit=False)
    ok, failed = [], []
    for t in tables:
        try:
            ddl = build_create_table(t)
        except Exception as e:
            print(f"  SKIP {t}: gagal introspeksi -- {e}", file=sys.stderr)
            failed.append((t, str(e)))
            continue
        if args.dry_run:
            print(f"-- === {t} ===")
            print(ddl)
            print()
            continue
        try:
            with pg_conn.cursor() as cur:
                cur.execute(ddl)
            pg_conn.commit()
            print(f"  OK    {t}", file=sys.stderr)
            ok.append(t)
        except Exception as e:
            pg_conn.rollback()
            print(f"  FAIL  {t}: {e}", file=sys.stderr)
            failed.append((t, str(e)))
    if pg_conn:
        pg_conn.close()
    print(f"\nSelesai: {len(ok)} tabel berhasil, {len(failed)} gagal.", file=sys.stderr)
    if failed:
        print("Gagal:", failed, file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
