-- Kepadatan penduduk per kabupaten/kota dari tabel dinamis BPS Web API
-- (webapi.bps.go.id, model=var/data, subjek Kependudukan) -- sumber
-- TAMBAHAN/cross-check utk C.A1 Kemanfaatan IJD, BUKAN pengganti
-- kecamatan_data_turunan (yang granularitasnya kecamatan, lebih halus
-- dari tabel ini yang cuma sampai kabupaten/kota).
--
-- Kenapa dibuat terpisah (bukan langsung isi kecamatan_data_turunan):
-- var_id "Kepadatan Penduduk menurut Kabupaten Kota" BEDA per provinsi
-- (tiap kantor BPS provinsi kelola tabel dinamisnya sendiri-sendiri) dan
-- KESEGARANNYA JUGA BEDA-BEDA -- provinsi tertentu update tahun 2024,
-- yang lain masih 2016-2021 atau tidak punya tabel ini sama sekali.
-- scripts/sync_kepadatan_kabupaten_bps_api.py mencari var_id yang tepat
-- per provinsi otomatis & merekam tahun datanya apa adanya -- jangan
-- asumsikan semua baris di tabel ini tahun yang sama.
--
-- Ditulis native PostgreSQL (bukan hasil migrasi MySQL) -- tabel baru
-- pasca migrasi 24 Jul 2026, lihat docs/migrasi_mysql_ke_postgresql.md.

CREATE TABLE IF NOT EXISTS bps_api_kepadatan_kabupaten (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_kabupaten      INT NOT NULL,          -- kode BPS 4 digit
  nama_kabupaten      VARCHAR(80) NOT NULL,  -- label 'vervar' dari BPS API (huruf besar)
  tahun               SMALLINT NOT NULL,     -- tahun data TERBARU yang tersedia utk provinsi ybs (bisa beda antar provinsi)
  kepadatan_per_km2   NUMERIC(10,2) NOT NULL,
  var_id              INT NOT NULL,          -- var_id BPS API asal data (beda per provinsi, utk audit/debug)
  disinkron_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (kode_kabupaten)  -- selalu overwrite ke data terbaru, bukan simpan historis multi-tahun
);
