-- Katalog link resmi publikasi "X Dalam Angka <tahun>" dari BPS Web API
-- (webapi.bps.go.id) per kabupaten/kota + provinsi -- pengganti hosting
-- ulang 9GB PDF dalam_angka/ di server: cukup simpan link ke publikasinya,
-- bukan file-nya. Diisi/disegarkan oleh scripts/sync_dalam_angka_bps_api.py
-- -- lihat catatan "dinamis tiap tahun" di situ.
--
-- PENTING soal url_publikasi: field 'pdf' dari BPS Web API berbentuk
-- download.php?f=<token terenkripsi>, BUKAN link halaman publikasi
-- permanen (dikonfirmasi 24 Jul 2026, contoh Kab. Simeulue Dalam Angka
-- 2026) -- kemungkinan token ini bisa kedaluwarsa. pub_id-lah yang stabil
-- (dipakai BPS sbg primary key publikasi mereka) -- kalau link tersimpan
-- ternyata sudah mati, re-query API pakai pub_id utk dapat token segar
-- (lihat fetch_fresh_pdf_url() di sync_dalam_angka_bps_api.py), jangan
-- asumsikan url_publikasi permanen.
--
-- Ditulis native PostgreSQL (bukan hasil migrasi MySQL) -- tabel baru
-- pasca migrasi 24 Jul 2026, lihat docs/migrasi_mysql_ke_postgresql.md.

CREATE TABLE IF NOT EXISTS dalam_angka_publikasi (
  id               INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kode_wilayah     INT NOT NULL,          -- kode BPS 2 digit (provinsi) atau 4 digit (kab/kota)
  jenis_wilayah    TEXT NOT NULL CHECK (jenis_wilayah IN ('PROVINSI', 'KABUPATEN_KOTA')),
  nama_wilayah     VARCHAR(80) NOT NULL,  -- nama sesuai judul publikasi BPS
  tahun            SMALLINT NOT NULL,     -- tahun edisi (dari judul, mis. "... Dalam Angka 2026")
  pub_id           VARCHAR(64),           -- ID publikasi BPS Web API (utk re-query, cek update)
  judul            VARCHAR(200) NOT NULL,
  url_publikasi    TEXT NOT NULL,         -- cache token 'pdf' dari BPS API, BISA KEDALUWARSA -- lihat catatan di atas
  tanggal_terbit   DATE,
  disinkron_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (kode_wilayah, tahun)
);

CREATE INDEX IF NOT EXISTS idx_dalam_angka_publikasi_kode_wilayah
  ON dalam_angka_publikasi (kode_wilayah);
